<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net6.0-windows;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Switcher</AssemblyName>
    <RootNamespace>Switcher</RootNamespace>
    <Version>0.4.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup Condition="$(TargetFramework.Contains('-windows'))">
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <OutputType>Exe</OutputType>
    <UseWindowsForms>false</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.Contains('-windows'))">
    <Using Include="System.IO" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <Compile Remove="TrayApp.cs" />
    <Compile Remove="SettingsForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WeCantSpell.Hunspell" Version="5.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="dict\*.aff;dict\*.dic;dict\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
